package bungo

import (
	"io/fs"
	"sync"
)

var (
	embeddedAssetsMu sync.RWMutex
	embeddedAssetsFS fs.FS
)

// RegisterEmbeddedAssetsFS registers a process-wide embedded asset filesystem used by BunGo servers.
// Inputs:
// - assets: filesystem containing project files generated by `bungo build` embedding.
// Outputs:
// - none
func RegisterEmbeddedAssetsFS(assets fs.FS) {
	embeddedAssetsMu.Lock()
	defer embeddedAssetsMu.Unlock()
	embeddedAssetsFS = assets
}

// getEmbeddedAssetsFS returns the currently registered embedded asset filesystem, if any.
// Inputs:
// - none
// Outputs:
// - fs.FS: registered embedded filesystem or nil when no embedded assets are available.
func getEmbeddedAssetsFS() fs.FS {
	embeddedAssetsMu.RLock()
	defer embeddedAssetsMu.RUnlock()
	return embeddedAssetsFS
}
