package scaffold

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	baseLayoutFile = `<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{if .PageTitle}}{{.PageTitle}}{{else}}BunGo Showcase{{end}}</title>
    <link rel="stylesheet" href="/static/styles.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="page-wrap">
        {{block "content" .}}{{end}}
    </div>
</body>
</html>
`
	homeTemplateFile = `{{define "content"}}
<header class="page-header">
    <h1>{{if .PageTitle}}{{.PageTitle}}{{else}}BunGo Showcase{{end}}</h1>
    <p>{{if .Subtitle}}{{.Subtitle}}{{else}}Go backend + embedded React frontend, no Node.js pipeline.{{end}}</p>
</header>

<section class="card">
    <h2>Server Features</h2>
    <ul>
        {{range .Features}}
        <li>{{.}}</li>
        {{end}}
    </ul>
</section>

<div id="root"></div>
{{end}}
`
	stylesCSSFile = `/* BunGo scaffold – baseline styles */
:root {
  --bg: #0f0f12;
  --surface: #1a1a20;
  --surface-hover: #22222a;
  --text: #e8e8ed;
  --text-muted: #9090a0;
  --accent: #6366f1;
  --accent-hover: #818cf8;
  --border: #2a2a32;
  --radius: 10px;
  --font: "DM Sans", -apple-system, BlinkMacSystemFont, sans-serif;
}

* { box-sizing: border-box; }

body {
  font-family: var(--font);
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  margin: 0;
  min-height: 100vh;
  padding: 0 1.5rem 3rem;
}

.page-wrap { max-width: 720px; margin: 0 auto; }

.page-header {
  padding: 2rem 0 1rem;
  border-bottom: 1px solid var(--border);
  margin-bottom: 2rem;
}

.page-header h1 { margin: 0 0 0.25rem; font-size: 1.75rem; font-weight: 600; color: var(--text); }
.page-header p { margin: 0; color: var(--text-muted); font-size: 0.95rem; }

.card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 1.75rem;
  margin-bottom: 1.5rem;
}

.card h2 {
  margin: 0 0 1rem;
  font-size: 1.25rem;
  font-weight: 600;
  color: var(--text);
  border-bottom: 1px solid var(--border);
  padding-bottom: 0.5rem;
}

.card p { margin: 0.5rem 0; color: var(--text-muted); font-size: 0.95rem; }
.card p:last-of-type { margin-bottom: 1rem; }

.btn {
  display: inline-block;
  background: var(--accent);
  color: #fff;
  font-family: inherit;
  font-weight: 600;
  font-size: 0.95rem;
  padding: 0.65rem 1.25rem;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.15s;
}

.btn:hover { background: var(--accent-hover); }
.btn.secondary { background: var(--surface-hover); color: var(--text); }
.btn.secondary:hover { background: var(--border); }

.muted { color: var(--text-muted); font-size: 0.9rem; }

#root { margin-top: 1rem; }

ul { margin: 0.5rem 0; padding-left: 1.25rem; }
`
	mainTemplate = `package main

import (
	"log"
	"time"

	bungo "github.com/piotr-nierobisz/BunGo"
	"github.com/piotr-nierobisz/BunGo/engine"
)

func main() {
	engineInstance := engine.NewHTTPEngine()
	srv := bungo.NewServer(engineInstance, "./web")
	srv.SetDefaultLayout("base.gohtml")

	srv.Security(bungo.SecurityLayer{
		Name: "require-demo-token",
		Handler: func(req *bungo.Request) bool {
			return req.Headers["Authorization"] == "Bearer demo-token"
		},
	})

	srv.Page(bungo.PageRoute{
		Path:          "/",
		Template:      "home.gohtml",
		View:          "%s",
		SecurityLayer: []string{"require-demo-token"},
		Handler: func(req *bungo.Request) (map[string]any, error) {
			return map[string]any{
				"PageTitle": "Welcome to BunGo",
				"Subtitle":  "This project was generated by bungo init.",
				"Features": []string{
					"Embedded React runtime",
					"Remote URL imports support",
					"Go templating + React hydration",
					"Security layers for shared auth checks",
				},
				"CounterStart": 3,
				"GeneratedAt":  time.Now().Format(time.RFC3339),
			}, nil
		},
	})

	srv.Api(bungo.ApiRoute{
		Path:    "/showcase",
		Version: "v1",
		Method:  "GET",
		Handler: func(req *bungo.Request) (bungo.APIResponse, error) {
			return bungo.APIResponse{
				StatusCode: 200,
				Body: map[string]any{
					"message": "BunGo API is working",
					"ok":      true,
				},
			}, nil
		},
	})

	log.Println("BunGo showcase running at http://localhost:3303")
	if err := srv.Serve(3303); err != nil {
		log.Fatal(err)
	}
}
`
	jsxViewFile = `import React, { useState, useEffect } from "react";
import { format } from "https://esm.sh/date-fns@3.6.0";

function ShowcaseApp() {
  const data = useBungoData();
  const [count, setCount] = useState(data.CounterStart ?? 0);
  const [apiResult, setApiResult] = useState(null);
  const [apiLoading, setApiLoading] = useState(true);
  const [apiError, setApiError] = useState(null);
  const [items, setItems] = useState(function () {
    return Array.isArray(data.Features) ? [...data.Features] : ["First item"];
  });
  const [inputValue, setInputValue] = useState("");

  useEffect(function () {
    fetch("/api/v1/showcase")
      .then(function (res) { return res.ok ? res.json() : Promise.reject(new Error("HTTP " + res.status)); })
      .then(function (body) { setApiResult(body); setApiError(null); })
      .catch(function (err) { setApiError(err.message); setApiResult(null); })
      .finally(function () { setApiLoading(false); });
  }, []);

  function addItem() {
    var text = inputValue.trim();
    if (!text) return;
    setItems(function (prev) { return [...prev, text]; });
    setInputValue("");
  }

  function removeItem(index) {
    setItems(function (prev) { return prev.filter(function (_, i) { return i !== index; }); });
  }

  var generatedAt = data.GeneratedAt
    ? format(new Date(data.GeneratedAt), "PPpp")
    : "unknown";

  return (
    <>
      <section className="card">
        <h2>Server data + remote import</h2>
        <p>Initial count from Go: {data.CounterStart ?? 0}. Formatted with date-fns: {generatedAt}</p>
        <button type="button" className="btn" onClick={() => setCount(function (v) { return v + 1; })}>Clicked {count} times</button>
      </section>

      <section className="card">
        <h2>API fetch (GET /api/v1/showcase)</h2>
        {apiLoading && <p className="muted">Loading…</p>}
        {apiError && <p className="muted" style={{ color: "var(--accent)" }}>Error: {apiError}</p>}
        {apiResult && !apiLoading && (
          <p className="muted">{apiResult.message} ok={String(apiResult.ok)}</p>
        )}
      </section>

      <section className="card">
        <h2>List state (add/remove)</h2>
        <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1rem" }}>
          <input
            type="text"
            value={inputValue}
            onChange={function (e) { setInputValue(e.target.value); }}
            onKeyDown={function (e) { if (e.key === "Enter") addItem(); }}
            placeholder="Add item"
            style={{ flex: 1, padding: "0.5rem 0.75rem", borderRadius: "8px", border: "1px solid var(--border)", background: "var(--surface)", color: "var(--text)" }}
          />
          <button type="button" className="btn" onClick={addItem}>Add</button>
        </div>
        <ul style={{ margin: 0, paddingLeft: "1.25rem" }}>
          {items.map(function (item, i) {
            return (
              <li key={i} style={{ marginBottom: "0.25rem", display: "flex", alignItems: "center", gap: "0.5rem" }}>
                <span>{item}</span>
                <button type="button" className="btn secondary" style={{ padding: "0.25rem 0.5rem", fontSize: "0.8rem" }} onClick={function () { removeItem(i); }}>Remove</button>
              </li>
            );
          })}
        </ul>
      </section>
    </>
  );
}

_bungoRender(ShowcaseApp);
`
	tsxViewFile = `import React, { useState, useEffect } from "react";
import { format } from "https://esm.sh/date-fns@3.6.0";

type ShowcaseData = {
  CounterStart?: number;
  GeneratedAt?: string;
  Features?: string[];
};

type ApiResponse = { message?: string; ok?: boolean } | null;

function ShowcaseApp() {
  const data = useBungoData() as ShowcaseData;
  const [count, setCount] = useState<number>(data.CounterStart ?? 0);
  const [apiResult, setApiResult] = useState<ApiResponse>(null);
  const [apiLoading, setApiLoading] = useState(true);
  const [apiError, setApiError] = useState<string | null>(null);
  const [items, setItems] = useState<string[]>(() =>
    Array.isArray(data.Features) ? [...data.Features] : ["First item"]
  );
  const [inputValue, setInputValue] = useState("");

  useEffect(() => {
    fetch("/api/v1/showcase")
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error("HTTP " + res.status))))
      .then((body: ApiResponse) => {
        setApiResult(body);
        setApiError(null);
      })
      .catch((err: Error) => {
        setApiError(err.message);
        setApiResult(null);
      })
      .finally(() => setApiLoading(false));
  }, []);

  function addItem() {
    const text = inputValue.trim();
    if (!text) return;
    setItems((prev) => [...prev, text]);
    setInputValue("");
  }

  function removeItem(index: number) {
    setItems((prev) => prev.filter((_, i) => i !== index));
  }

  const generatedAt = data.GeneratedAt
    ? format(new Date(data.GeneratedAt), "PPpp")
    : "unknown";

  return (
    <>
      <section className="card">
        <h2>Server data + remote import</h2>
        <p>Initial count from Go: {data.CounterStart ?? 0}. Formatted with date-fns: {generatedAt}</p>
        <button type="button" className="btn" onClick={() => setCount((v) => v + 1)}>Clicked {count} times</button>
      </section>

      <section className="card">
        <h2>API fetch (GET /api/v1/showcase)</h2>
        {apiLoading && <p className="muted">Loading…</p>}
        {apiError && <p className="muted" style={{ color: "var(--accent)" }}>Error: {apiError}</p>}
        {apiResult && !apiLoading && (
          <p className="muted">{apiResult.message} ok={String(apiResult?.ok)}</p>
        )}
      </section>

      <section className="card">
        <h2>List state (add/remove)</h2>
        <div style={{ display: "flex", gap: "0.5rem", marginBottom: "1rem" }}>
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && addItem()}
            placeholder="Add item"
            style={{ flex: 1, padding: "0.5rem 0.75rem", borderRadius: "8px", border: "1px solid var(--border)", background: "var(--surface)", color: "var(--text)" }}
          />
          <button type="button" className="btn" onClick={addItem}>Add</button>
        </div>
        <ul style={{ margin: 0, paddingLeft: "1.25rem" }}>
          {items.map((item, i) => (
            <li key={i} style={{ marginBottom: "0.25rem", display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <span>{item}</span>
              <button type="button" className="btn secondary" style={{ padding: "0.25rem 0.5rem", fontSize: "0.8rem" }} onClick={() => removeItem(i)}>Remove</button>
            </li>
          ))}
        </ul>
      </section>
    </>
  );
}

_bungoRender(ShowcaseApp);
`
	tsConfigFile = `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "jsx": "react-jsx",
    "strict": true,
    "isolatedModules": true,
    "skipLibCheck": true,
    "allowJs": true
  },
  "include": ["web/views/**/*", "bungo-env.d.ts"]
}
`
	bungoEnvDTS = `// BunGo-injected globals (no import needed)
declare function useBungoData(): any;
declare function _bungoRender(component: any, elementId?: string): void;
`
)

// InitProject scaffolds a BunGo showcase application.
func InitProject(projectName string, useTypescript bool) (string, error) {
	if strings.TrimSpace(projectName) == "" {
		return "", errors.New("project name is required")
	}
	if strings.Contains(projectName, string(filepath.Separator)) || strings.Contains(projectName, "/") {
		return "", fmt.Errorf("project name must be a single directory name, got %q", projectName)
	}

	targetDir := filepath.Join(".", projectName)
	if _, err := os.Stat(targetDir); err == nil {
		return "", fmt.Errorf("target directory %q already exists", projectName)
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", fmt.Errorf("unable to access target directory %q: %w", projectName, err)
	}

	if err := os.MkdirAll(filepath.Join(targetDir, "web", "layouts"), 0o755); err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Join(targetDir, "web", "views"), 0o755); err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Join(targetDir, "web", "static"), 0o755); err != nil {
		return "", err
	}

	viewName := "showcase.jsx"
	viewContent := jsxViewFile
	if useTypescript {
		viewName = "showcase.tsx"
		viewContent = tsxViewFile
	}

	files := map[string]string{
		"go.mod":  fmt.Sprintf("module %s\n\ngo 1.25.0\n", projectName),
		"main.go": fmt.Sprintf(mainTemplate, viewName),
		filepath.Join("web", "layouts", "base.gohtml"): baseLayoutFile,
		filepath.Join("web", "layouts", "home.gohtml"): homeTemplateFile,
		filepath.Join("web", "views", viewName):        viewContent,
		filepath.Join("web", "static", "styles.css"):   stylesCSSFile,
	}

	if useTypescript {
		files["tsconfig.json"] = tsConfigFile
		files["bungo-env.d.ts"] = bungoEnvDTS
	}

	for relPath, content := range files {
		fullPath := filepath.Join(targetDir, relPath)
		if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
			return "", fmt.Errorf("writing %s failed: %w", relPath, err)
		}
	}

	return filepath.Abs(targetDir)
}
